import type { PerfilCreateInput } from "@/lib/perfiles-schema";

/**
 * Catálogo seed de perfiles de extracción.
 *
 * Cada item representa una entidad (banco o billetera) con su perfil
 * default de "extracto bancario en pesos". Es el punto de partida del
 * catálogo: el admin puede crear más perfiles por entidad (tarjetas,
 * USD, etc.) vía /api/perfiles.
 *
 * Las palabras clave son señales que el detector le pasa a OpenAI para
 * mapear texto → perfil. Tienen que ser específicas de la entidad
 * (razón social, mensajes legales típicos, CBU prefix, etc.).
 */
export const PERFILES_SEED: PerfilCreateInput[] = [
  {
    slug: "galicia_extracto_ars",
    entidad: { slug: "galicia", nombre: "Banco Galicia", iconoUrl: null },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: [
        "Banco Galicia",
        "Galicia",
        "Banco de Galicia y Buenos Aires",
        "BGAL",
      ],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 10,
    activo: true,
  },
  {
    slug: "nacion_extracto_ars",
    entidad: { slug: "nacion", nombre: "Banco Nación", iconoUrl: null },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: [
        "Banco de la Nación Argentina",
        "Banco Nación",
        "BNA",
      ],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 20,
    activo: true,
  },
  {
    slug: "provincia_extracto_ars",
    entidad: {
      slug: "provincia",
      nombre: "Banco Provincia",
      iconoUrl: null,
    },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: [
        "Banco de la Provincia de Buenos Aires",
        "Banco Provincia",
        "BAPRO",
      ],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 30,
    activo: true,
  },
  {
    slug: "ciudad_extracto_ars",
    entidad: {
      slug: "ciudad",
      nombre: "Banco Ciudad",
      iconoUrl: null,
    },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: [
        "Banco Ciudad",
        "Banco de la Ciudad de Buenos Aires",
        "BCBA",
      ],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 40,
    activo: true,
  },
  {
    slug: "santander_extracto_ars",
    entidad: {
      slug: "santander",
      nombre: "Banco Santander",
      iconoUrl: null,
    },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: [
        "Santander",
        "Banco Santander Argentina",
        "Santander Río",
      ],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 50,
    activo: true,
  },
  {
    slug: "bbva_extracto_ars",
    entidad: { slug: "bbva", nombre: "BBVA Argentina", iconoUrl: null },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: ["BBVA", "BBVA Argentina", "BBVA Francés"],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 60,
    activo: true,
  },
  {
    slug: "macro_extracto_ars",
    entidad: { slug: "macro", nombre: "Banco Macro", iconoUrl: null },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: ["Banco Macro", "Macro S.A."],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 70,
    activo: true,
  },
  {
    slug: "icbc_extracto_ars",
    entidad: { slug: "icbc", nombre: "ICBC", iconoUrl: null },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: [
        "ICBC",
        "Industrial and Commercial Bank of China",
        "ICBC Argentina",
      ],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 80,
    activo: true,
  },
  {
    slug: "hsbc_extracto_ars",
    entidad: { slug: "hsbc", nombre: "HSBC Argentina", iconoUrl: null },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: ["HSBC", "HSBC Bank Argentina"],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 90,
    activo: true,
  },
  {
    slug: "supervielle_extracto_ars",
    entidad: {
      slug: "supervielle",
      nombre: "Banco Supervielle",
      iconoUrl: null,
    },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: ["Supervielle", "Banco Supervielle"],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 100,
    activo: true,
  },
  {
    slug: "patagonia_extracto_ars",
    entidad: {
      slug: "patagonia",
      nombre: "Banco Patagonia",
      iconoUrl: null,
    },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: ["Banco Patagonia", "Patagonia S.A."],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 110,
    activo: true,
  },
  {
    slug: "credicoop_extracto_ars",
    entidad: {
      slug: "credicoop",
      nombre: "Banco Credicoop",
      iconoUrl: null,
    },
    categoria: "banco",
    nombre: "Extracto Caja de Ahorro ARS",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: [
        "Banco Credicoop",
        "Credicoop Cooperativo Limitado",
      ],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 120,
    activo: true,
  },
  {
    slug: "mercado_pago_extracto_ars",
    entidad: {
      slug: "mercado_pago",
      nombre: "Mercado Pago",
      iconoUrl: null,
    },
    categoria: "billetera",
    nombre: "Extracto Cuenta Mercado Pago",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: [
        "Mercado Pago",
        "MercadoPago",
        "Mercado Pago S.R.L.",
        "PVCM",
      ],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 200,
    activo: true,
  },
  {
    slug: "uala_extracto_ars",
    entidad: { slug: "uala", nombre: "Ualá", iconoUrl: null },
    categoria: "billetera",
    nombre: "Extracto Cuenta Ualá",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: ["Ualá", "Uala", "Uilo S.A."],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 210,
    activo: true,
  },
  {
    slug: "naranja_x_extracto_ars",
    entidad: {
      slug: "naranja_x",
      nombre: "Naranja X",
      iconoUrl: null,
    },
    categoria: "billetera",
    nombre: "Extracto Cuenta Naranja X",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: ["Naranja X", "NaranjaX", "Tarjeta Naranja"],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 220,
    activo: true,
  },
  {
    slug: "cuenta_dni_extracto_ars",
    entidad: {
      slug: "cuenta_dni",
      nombre: "Cuenta DNI",
      iconoUrl: null,
    },
    categoria: "billetera",
    nombre: "Extracto Cuenta DNI",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: ["Cuenta DNI", "CuentaDNI", "Banco Provincia DNI"],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 230,
    activo: true,
  },
  {
    slug: "personal_pay_extracto_ars",
    entidad: {
      slug: "personal_pay",
      nombre: "Personal Pay",
      iconoUrl: null,
    },
    categoria: "billetera",
    nombre: "Extracto Cuenta Personal Pay",
    tipoDocumento: "extracto_bancario",
    monedaPrimaria: "ARS",
    promptSistema: "",
    huella: {
      palabrasClave: ["Personal Pay", "PersonalPay", "Telecom Argentina"],
    },
    validacionesEspeciales: [],
    ordenEnGrid: 240,
    activo: true,
  },
];
